### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by johanwilfer** [PaysonAktiebolag/PaysonPayments-PHP#1]
We are considering changing to this SDK instead of our home-grown API implementation. But the lack of composer support is a bit surprising to me at a time more or less everyone has moved there.

How are the plans for composer? Could you add it? Or are there another more supported library?

If no on these questions - would you accept pull requests adding this?

**Comment by PaysonAB** [comment]
Hi Johan,
We don't have any plans for adding composer support at this time.
This is the most current PHP SDK for Payson Checkout and Payson Recurring Payments.
We would most likely accept a pull request adding composer support as long as it can co-exist with the current include approach.

**Comment by johanwilfer** [comment]
Thanks a lot then, we will look into contributing that.

**Comment by minhphuc102102** [comment]
hi @PaysonAB  , i am developer , i need support composer to plugin run , please help me !!!

**Comment by PaysonAB** [comment]
Composer support added. Use composer require payson/paysonpayments

**Comment by minhphuc102102** [comment]
Thanks you so much !!!
