### ISSUE TITLE
License for SDK missing?

### ISSUE THREAD

**Issue by johanwilfer** [PaysonAktiebolag/PaysonPayments-PHP#2]
What license is this SDK released as? I found no information about that in this repository.

**Comment by PaysonAB** [comment]
It's http://unlicense.org/

**Comment by johanwilfer** [comment]
Will you update the code to reflect this? Add a LICENCE file for example. https://help.github.com/en/articles/licensing-a-repository

**Comment by PaysonAB** [comment]
It's added now. Thank you!

**Comment by johanwilfer** [comment]
Perfect, thanks a lot!
